# Generated by Django 4.2.5 on 2025-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
                ('release_date', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=40)),
                ('developer', models.CharField(max_length=100)),
                ('magnet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MagnetLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateAdded', models.DateTimeField()),
                ('AbsolutePath', models.CharField(max_length=512)),
                ('AbsoluteUri', models.CharField(max_length=512)),
                ('Authority', models.CharField(max_length=512)),
                ('Host', models.CharField(max_length=128)),
                ('Port', models.IntegerField()),
                ('Scheme', models.CharField(max_length=32)),
                ('Version', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image_url', models.TextField()),
                ('release_date', models.CharField(max_length=20)),
                ('synopsis', models.TextField()),
                ('quality_720p', models.TextField(default='NULL')),
                ('quality_720p_size', models.CharField(default='NULL', max_length=20)),
                ('quality_1080p', models.TextField(default='NULL')),
                ('quality_1080p_size', models.CharField(default='NULL', max_length=20)),
            ],
        ),
    ]
