version: '3.7'

services:
  torrents-tracker:
    container_name: torrents-tracker
    build: .
    command: python manage.py runserver 0.0.0.0:7070
    volumes:
      - .:/app
      - /tmp/torrents-tracker:/tmp
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "7070:7070"
    network_mode: bridge

networks:
  default:
    driver: bridge
