# ┌────────────────────────────────────────────────────────────────────────────────┐
# │                                                                                │
# │   torrents-tracker                                                             │
# │                                                                                │
# │   Dockerfile                                                                   │
# │                                                                                │
# ┼────────────────────────────────────────────────────────────────────────────────┼
# │   Guillaume Plante  <guillaumeplante.qc@gmail.com>                             │
# └────────────────────────────────────────────────────────────────────────────────┘

# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory inside the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libjpeg-dev \
    libxml2-dev \
    libxslt1-dev \
    && rm -rf /var/lib/apt/lists/*

# Install pip and upgrade to the latest version
RUN pip install --upgrade pip

# Copy the requirements file
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# Copy the Django project code into the container
COPY . /app/

# Expose port 7070 for the Django application
EXPOSE 7070

# Command to run the Django development server on 0.0.0.0:7070
CMD ["python", "manage.py", "collectstatic", "--noinput"]


